version: "3.3"
name: grafana-test
services:
  grafana.service:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 3000:3000

  mongodb-exporter:
    image: percona/mongodb_exporter:0.39.0
    container_name: mongodb-exporter
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 9216:9216
    environment:
      - MONGODB_URI=${MONGO_CONNECTION_STRING}

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 9090:9090
    environment:
      - MONGODB_URI=${MONGO_CONNECTION_STRING}
    volumes:
      - ./prometheus/data:/etc/prometheus/

networks:
  backend:
    name: mongo-db-test_mongo-backend
    external: true

volumes:
  mongodbdata:
    driver: local
  prometheus-data:
    driver: local
