version: "3.3"
name: grafana-test
services:
  grafana.service:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 3000:3000

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
