version: "3.3"
name: mongo-db-test
services:
  : image: mongo:7.0.0
    container_name: mongodb
    restart: unless-stopped
    #command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: clidb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - mongo-backend
    ports:
      - 27000:27017

  mongo-express.service:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb.service
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      #ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
      #ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test12345
    networks:
      - mongo-backend
    ports:
      - 8081:8081
    volumes:
      - mongodbdata:/data/db
    depends_on:
      - mongodb.service

networks:
  mongo-backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
