version: "3"
services:
  mongodb:
    image: mongo:7.0.0
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: clidb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
    ports:
      - 27000:27017

networks:
  backend:
    driver: bridge

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
